// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/capability.h>
#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

#define MAX_FDS 30

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  } else if (strncmp(fs, "gfs2", 4) == 0 &&
             (strstr(opts, "errors=panic") || strstr(opts, "debug"))) {
    strcat(opts, ",errors=withdraw");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

static void setup_gadgetfs();
static void setup_binderfs();
static void setup_fusectl();
static void sandbox_common_mount_tmpfs(void)
{
  write_file("/proc/sys/fs/mount-max", "100000");
  if (mkdir("./syz-tmp", 0777))
    exit(1);
  if (mount("", "./syz-tmp", "tmpfs", 0, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot", 0777))
    exit(1);
  if (mkdir("./syz-tmp/newroot/dev", 0700))
    exit(1);
  unsigned bind_mount_flags = MS_BIND | MS_REC | MS_PRIVATE;
  if (mount("/dev", "./syz-tmp/newroot/dev", NULL, bind_mount_flags, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot/proc", 0700))
    exit(1);
  if (mount("syz-proc", "./syz-tmp/newroot/proc", "proc", 0, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot/selinux", 0700))
    exit(1);
  const char* selinux_path = "./syz-tmp/newroot/selinux";
  if (mount("/selinux", selinux_path, NULL, bind_mount_flags, NULL)) {
    if (errno != ENOENT)
      exit(1);
    if (mount("/sys/fs/selinux", selinux_path, NULL, bind_mount_flags, NULL) &&
        errno != ENOENT)
      exit(1);
  }
  if (mkdir("./syz-tmp/newroot/sys", 0700))
    exit(1);
  if (mount("/sys", "./syz-tmp/newroot/sys", 0, bind_mount_flags, NULL))
    exit(1);
  if (mount("/sys/kernel/debug", "./syz-tmp/newroot/sys/kernel/debug", NULL,
            bind_mount_flags, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mount("/sys/fs/smackfs", "./syz-tmp/newroot/sys/fs/smackfs", NULL,
            bind_mount_flags, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mount("/proc/sys/fs/binfmt_misc",
            "./syz-tmp/newroot/proc/sys/fs/binfmt_misc", NULL, bind_mount_flags,
            NULL) &&
      errno != ENOENT)
    exit(1);
  if (mkdir("./syz-tmp/newroot/syz-inputs", 0700))
    exit(1);
  if (mount("/syz-inputs", "./syz-tmp/newroot/syz-inputs", NULL,
            bind_mount_flags | MS_RDONLY, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mkdir("./syz-tmp/pivot", 0777))
    exit(1);
  if (syscall(SYS_pivot_root, "./syz-tmp", "./syz-tmp/pivot")) {
    if (chdir("./syz-tmp"))
      exit(1);
  } else {
    if (chdir("/"))
      exit(1);
    if (umount2("./pivot", MNT_DETACH))
      exit(1);
  }
  if (chroot("./newroot"))
    exit(1);
  if (chdir("/"))
    exit(1);
  setup_gadgetfs();
  setup_binderfs();
  setup_fusectl();
}

static void setup_gadgetfs()
{
  if (mkdir("/dev/gadgetfs", 0777)) {
  }
  if (mount("gadgetfs", "/dev/gadgetfs", "gadgetfs", 0, NULL)) {
  }
}

static void setup_fusectl()
{
  if (mount(0, "/sys/fs/fuse/connections", "fusectl", 0, 0)) {
  }
}

static void setup_binderfs()
{
  if (mkdir("/dev/binderfs", 0777)) {
  }
  if (mount("binder", "/dev/binderfs", "binder", 0, NULL)) {
  }
  if (symlink("/dev/binderfs", "./binderfs")) {
  }
}

static void loop();

static void sandbox_common()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  if (getppid() == 1)
    exit(1);
  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = (200 << 20);
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 32 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 136 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 128 << 20;
  setrlimit(RLIMIT_CORE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 256;
  setrlimit(RLIMIT_NOFILE, &rlim);
  if (unshare(CLONE_NEWNS)) {
  }
  if (mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, NULL)) {
  }
  if (unshare(CLONE_NEWIPC)) {
  }
  if (unshare(0x02000000)) {
  }
  if (unshare(CLONE_NEWUTS)) {
  }
  if (unshare(CLONE_SYSVSEM)) {
  }
  typedef struct {
    const char* name;
    const char* value;
  } sysctl_t;
  static const sysctl_t sysctls[] = {
      {"/proc/sys/kernel/shmmax", "16777216"},
      {"/proc/sys/kernel/shmall", "536870912"},
      {"/proc/sys/kernel/shmmni", "1024"},
      {"/proc/sys/kernel/msgmax", "8192"},
      {"/proc/sys/kernel/msgmni", "1024"},
      {"/proc/sys/kernel/msgmnb", "1024"},
      {"/proc/sys/kernel/sem", "1024 1048576 500 1024"},
  };
  unsigned i;
  for (i = 0; i < sizeof(sysctls) / sizeof(sysctls[0]); i++)
    write_file(sysctls[i].name, sysctls[i].value);
}

static int wait_for_loop(int pid)
{
  if (pid < 0)
    exit(1);
  int status = 0;
  while (waitpid(-1, &status, __WALL) != pid) {
  }
  return WEXITSTATUS(status);
}

static void drop_caps(void)
{
  struct __user_cap_header_struct cap_hdr = {};
  struct __user_cap_data_struct cap_data[2] = {};
  cap_hdr.version = _LINUX_CAPABILITY_VERSION_3;
  cap_hdr.pid = getpid();
  if (syscall(SYS_capget, &cap_hdr, &cap_data))
    exit(1);
  const int drop = (1 << CAP_SYS_PTRACE) | (1 << CAP_SYS_NICE);
  cap_data[0].effective &= ~drop;
  cap_data[0].permitted &= ~drop;
  cap_data[0].inheritable &= ~drop;
  if (syscall(SYS_capset, &cap_hdr, &cap_data))
    exit(1);
}

static int do_sandbox_none(void)
{
  if (unshare(CLONE_NEWPID)) {
  }
  int pid = fork();
  if (pid != 0)
    return wait_for_loop(pid);
  sandbox_common();
  drop_caps();
  if (unshare(CLONE_NEWNET)) {
  }
  write_file("/proc/sys/net/ipv4/ping_group_range", "0 65535");
  sandbox_common_mount_tmpfs();
  loop();
  exit(1);
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void reset_loop()
{
  char buf[64];
  snprintf(buf, sizeof(buf), "/dev/loop%llu", procid);
  int loopfd = open(buf, O_RDWR);
  if (loopfd != -1) {
    ioctl(loopfd, LOOP_CLR_FD, 0);
    close(loopfd);
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void close_fds()
{
  for (int fd = 3; fd < MAX_FDS; fd++)
    close(fd);
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    reset_loop();
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      close_fds();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[1] = {0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  prctl$PR_SET_SYSCALL_USER_DISPATCH_ON arguments: [
  //    option: const = 0x3b (8 bytes)
  //    mode: const = 0x1 (8 bytes)
  //    offset: intptr = 0x8 (8 bytes)
  //    len: intptr = 0x1 (8 bytes)
  //    selector: ptr[in, int8] {
  //      int8 = 0x0 (1 bytes)
  //    }
  //  ]
  *(uint8_t*)0x200000000040 = 0;
  syscall(__NR_prctl, /*option=*/0x3bul, /*mode=*/1ul, /*offset=*/8ul,
          /*len=*/1ul, /*selector=*/0x200000000040ul);
  //  syz_mount_image$udf arguments: [
  //    fs: ptr[in, buffer] {
  //      buffer: {75 64 66 00} (length 0x4)
  //    }
  //    dir: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 30 00} (length 0x8)
  //    }
  //    flags: mount_flags = 0x0 (8 bytes)
  //    opts: ptr[inout, array[ANYUNION]] {
  //      array[ANYUNION] {
  //        union ANYUNION {
  //          ANYBLOB: buffer: {00 41 66 f2 c2 86 f3 ec 44 c7 64 24 b9 78 b0 d3
  //          b0 cc 42 10 13 53 32 a7 00} (length 0x19)
  //        }
  //      }
  //    }
  //    chdir: int8 = 0x1 (1 bytes)
  //    size: len = 0x46f (8 bytes)
  //    img: ptr[in, buffer] {
  //      buffer: (compressed buffer with length 0x46f)
  //    }
  //  ]
  //  returns fd_dir
  memcpy((void*)0x200000000480, "udf\000", 4);
  memcpy((void*)0x2000000004c0, "./file0\000", 8);
  memcpy((void*)0x200000003280,
         "\x00\x41\x66\xf2\xc2\x86\xf3\xec\x44\xc7\x64\x24\xb9\x78\xb0\xd3\xb0"
         "\xcc\x42\x10\x13\x53\x32\xa7\x00",
         25);
  memcpy(
      (void*)0x200000000540,
      "\x78\x9c\xec\xdb\xcd\x6f\x1b\x55\x17\xc7\xf1\xdf\x9d\xd8\xee\xd4\xad\x9e"
      "\xc7\x6d\x43\x4b\x51\x23\x8c\x90\x68\x55\x44\x9a\x38\x6f\x15\x01\xa4\x34"
      "\x2f\x52\xa5\x26\x85\xa6\xc9\x82\x45\xa4\x90\x38\xc1\xaa\xe3\x44\x71\x1a"
      "\x35\x55\x44\xb3\x80\x0d\x7f\x00\x2b\x16\x6c\x10\x88\x45\x28\x1b\x16\xac"
      "\xd8\x54\x48\x15\x12\x1b\x36\x80\xc4\xa6\x15\x5b\xcc\x86\x2e\x41\x33\x9e"
      "\xf1\x8c\x5d\xa7\x09\x75\x6c\x27\xe9\xf7\x23\xb5\xbe\x1e\x1f\xcf\xdc\xb9"
      "\xc7\x9e\x7b\xee\x28\x16\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x90"
      "\x2e\x0d\x0f\x74\x74\x9a\x66\xf7\x02\x00\x00\x34\xd2\xd8\xf8\xb5\x8e\x14"
      "\xf3\x3f\x00\x00\xcf\x94\xeb\xac\xff\x01\x00\x00\x9e\x25\x46\x96\x56\x65"
      "\x34\xf8\x57\xc1\x8c\xba\xcf\x8b\xec\x2b\x99\xdc\xcd\x5b\x13\x43\x23\xd5"
      "\xdf\x76\xd8\xb8\xef\x6c\x71\xe3\x9d\x7f\x76\x67\xaa\xab\xbb\xa7\xb7\xef"
      "\xa2\xff\xf8\xe4\xf7\xef\xb6\xd3\xba\x3a\x7e\x7d\x20\x39\xb8\xb8\xb0\xb4"
      "\x9c\xce\xe7\xd3\xb3\xc9\x89\x5c\x66\x66\x71\x36\xbd\xe3\x3d\xd4\xfa\xfe"
      "\x4a\xe7\xdd\x01\x48\x2e\xdc\xb8\x39\x3b\x37\x97\x4f\xa6\xda\xbb\xca\x5e"
      "\xbe\x95\xf8\xe3\xd0\x91\x93\x89\xfe\xde\xc9\xd4\x90\x1f\x3b\x31\x34\x32"
      "\x32\x1e\x8a\x89\x44\x9f\xfa\xe8\x8f\xd9\xaa\xc2\x8f\xc9\xd2\x9b\x32\xba"
      "\x60\x6f\x9a\x31\x49\x96\x6a\x1f\x8b\x6d\x3e\x3b\xf5\x76\xd8\x3d\x89\xf3"
      "\xee\x49\x4c\x0c\x8d\xb8\x27\x92\xcd\x4c\xe7\x56\x9c\x17\x8d\x3f\x10\x56"
      "\xf9\x98\xc4\xfc\x31\x6a\x40\x2e\x6a\x62\x49\x4e\xbf\x4c\x6c\x77\xd6\x6c"
      "\x51\x59\x7a\x45\x46\xf7\x5b\x0b\xe6\xaa\xa4\x16\x7f\x1c\x5e\x75\x6f\x0c"
      "\xef\xa8\x3f\xcd\x10\x71\x96\xae\x92\xce\x69\x1f\xe4\x6c\x0f\x3b\x24\x4b"
      "\x53\x32\xba\x77\x21\xa1\xb7\xbd\x71\x75\xf3\x1f\x93\xd6\x9b\xdd\x39\xd4"
      "\x5d\x44\x96\x36\x65\x74\xf6\xad\x82\x79\xc7\xbd\x1e\x38\xdf\x27\xe7\xb2"
      "\x79\x65\x32\x79\x39\x37\xb7\x18\x8a\x35\xc6\xfb\x46\xed\xf7\xf9\xa1\x91"
      "\xf6\xf8\xb5\xc9\x96\xa5\x31\xf7\x1b\x5f\x30\xd7\x9a\xdd\x19\x34\x9c\x53"
      "\x2c\xa5\x64\xf4\xf5\xe6\xaa\x5b\x57\xc8\xad\x4b\xff\xdf\xdf\xf7\xe2\xe9"
      "\xcb\xe1\x0a\xe3\xd4\x36\xfb\x71\x62\xdb\x25\xc5\x77\x38\x27\x47\x43\xa5"
      "\x83\x69\x52\x0d\x01\xc9\x36\x96\x1e\xca\xe8\xd1\x2f\xb6\xfb\xfc\x9c\x3f"
      "\x07\x48\xdf\xff\xd3\xdc\xae\xa1\x11\x8c\xa5\xac\x8c\xbe\xf8\xa9\xe0\x2e"
      "\x8d\xc2\xeb\xd2\x96\xd0\xfa\xbe\x64\xbf\xcf\xfd\xf5\xed\xff\x61\x7b\x70"
      "\x71\x69\x6d\x39\x33\xff\xfe\x4a\xd5\xd7\xe3\xf6\xc0\x7b\xf9\x95\xe5\xe9"
      "\x99\xea\x2f\x17\xd7\xae\x65\x97\xc3\xed\xd6\xb1\x35\x8a\x1a\x4b\xc3\x32"
      "\x9a\xea\xfa\xb2\x74\x19\xf6\xd6\x00\x91\xe2\xb3\x96\x52\xec\xe7\x6f\x04"
      "\x7d\xb3\x2b\x8f\xef\x7e\x6e\xfe\x57\xbc\x9f\xe1\xcf\x21\x6d\xef\xb6\x86"
      "\xdb\x55\xbb\xfc\x1f\xea\x23\xe7\x98\xc6\x58\x7a\x20\xa3\xb9\xa9\xe7\xdd"
      "\xbe\x18\x67\xc6\xa9\x1c\x33\x15\xe3\x3e\x92\xd1\x70\xdb\x19\x2f\xce\x8a"
      "\x39\x0d\xff\x6c\x12\xc5\x3d\xce\x65\xb2\xe9\x0e\x27\x76\x43\x46\x3f\x7c"
      "\xe2\xc7\xba\xb7\x45\x4a\x85\xe2\x89\x20\xb6\xd3\x89\x1d\x95\xd1\xeb\x85"
      "\xf2\xd8\xb8\x17\xdb\x1a\xc4\xa6\x9c\xd8\x15\x19\xe5\x1e\x54\x8f\x7d\x2e"
      "\x88\xed\x72\x62\x5f\x92\xd1\xea\x87\x49\x3f\x36\xee\x34\xda\xbc\xd8\x93"
      "\x41\x6c\xfb\xcc\x62\x76\xb6\xda\x50\x3e\x0d\x27\xff\x77\x64\x34\x1a\x4d"
      "\x1a\x7f\x6c\xb6\xcc\xff\x7a\x70\x2d\xd8\xa8\xdc\xd1\x16\x39\xaf\x35\xff"
      "\x89\xd0\xb6\x0d\x2f\xaf\x0f\xbd\xfc\xb7\x6c\x93\xff\x1f\x65\x74\xff\xf7"
      "\x33\xfe\x3d\x0d\x77\xec\xbd\x93\xd2\x31\xf7\xff\x20\xff\xf7\x64\x64\x3e"
      "\x2b\x8f\xb5\xbd\xd8\xe3\x41\x6c\xe7\x8e\x07\x76\x9f\x70\xf2\xbf\x2e\xa3"
      "\xcc\xe4\xdd\xd2\xd8\x78\xf9\xf7\x32\x10\x64\x2d\x9c\xff\x17\x2a\x3f\x1d"
      "\x75\xca\xff\xb1\xd0\xb6\x84\x77\xdc\x3d\xb2\x74\x3a\x10\xf2\x6b\xb7\x6f"
      "\x4c\x67\xb3\xe9\x65\x1a\x34\x68\xd0\x28\x35\x9a\x7d\x65\x42\x23\x38\xf3"
      "\x7f\x9b\x8c\x2e\xfd\xf9\x5b\xa9\xde\xf1\xe6\xff\xa3\xc5\x67\x41\xfd\xf7"
      "\xe8\x83\x60\xfe\xef\xaf\xdc\x51\x9d\xe6\xff\xe3\xa1\x6d\xfd\x5e\x35\x12"
      "\x8d\x48\xf6\xca\xc2\x52\xf4\x94\x64\xe7\xd7\x6e\xbf\x96\x59\x98\x9e\x4f"
      "\xcf\xa7\x73\x9d\x17\xfb\x7a\xba\x7b\xfb\xba\x7b\xba\xa3\x31\xbf\xb8\x0b"
      "\x5a\x35\x8f\xd5\x41\xe4\xe4\xff\x3b\x19\xfd\x6d\x7f\x55\x5a\xef\x94\xd7"
      "\x7f\xd5\xeb\xff\x78\xe5\x8e\xea\x94\xff\x13\xa1\x6d\xf1\xb2\x7a\xa5\xe6"
      "\x53\x87\x97\x7f\x67\xdd\xf9\xf3\xc7\x77\x4b\x39\x7d\x52\xfd\xef\xaf\xb3"
      "\xce\xbd\x5c\x7c\x2c\x7d\x3f\xeb\x94\xff\xd6\xd0\xb6\x84\x77\xdc\x23\xbb"
      "\x73\xea\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0\xaf\x45"
      "\x8d\xa5\x6f\x65\xf4\xcd\xaf\x11\xe3\xff\xd6\x68\x27\x7f\xff\xf7\xd8\x0f"
      "\x90\xea\xf4\xf7\x5f\x27\x43\xdb\x66\x1b\xf4\x7b\x85\x9a\x07\x15\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x68\x12\x4b\x96\x3e\x95\xd1\x59\x15\xcc\x1d"
      "\x67\xc3\x51\x69\x34\xfc\x88\x03\xed\xdf\x00\x00\x00\xff\xff\x98\x2a\x22"
      "\x67",
      1135);
  syz_mount_image(/*fs=*/0x200000000480, /*dir=*/0x2000000004c0, /*flags=*/0,
                  /*opts=*/0x200000003280, /*chdir=*/1, /*size=*/0x46f,
                  /*img=*/0x200000000540);
  //  creat arguments: [
  //    file: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 31 00} (length 0x8)
  //    }
  //    mode: open_mode = 0x104 (8 bytes)
  //  ]
  //  returns fd
  memcpy((void*)0x200000000380, "./file1\000", 8);
  res = syscall(__NR_creat, /*file=*/0x200000000380ul,
                /*mode=S_IROTH|S_IRUSR*/ 0x104ul);
  if (res != -1)
    r[0] = res;
  //  truncate arguments: [
  //    file: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 31 00} (length 0x8)
  //    }
  //    len: intptr = 0xeba (8 bytes)
  //  ]
  memcpy((void*)0x200000000240, "./file1\000", 8);
  syscall(__NR_truncate, /*file=*/0x200000000240ul, /*len=*/0xebaul);
  //  write$binfmt_elf64 arguments: [
  //    fd: fd_binfmt (resource)
  //    data: ptr[in, binfmt_elf[int64, elf64_phdr, ELF64_PHDR_SIZE]] {
  //      binfmt_elf[int64, elf64_phdr, ELF64_PHDR_SIZE] {
  //        hdr: elf_hdr[int64, ELF64_PHDR_SIZE] {
  //          e_ident0: const = 0x7f (1 bytes)
  //          e_ident1: const = 0x45 (1 bytes)
  //          e_ident2: const = 0x4c (1 bytes)
  //          e_ident3: const = 0x46 (1 bytes)
  //          e_ident_class: int8 = 0x35 (1 bytes)
  //          e_ident_data: int8 = 0x6 (1 bytes)
  //          e_ident_ver: int8 = 0x5 (1 bytes)
  //          e_ident_osabi: int8 = 0x0 (1 bytes)
  //          e_ident_pad: int64 = 0xfffffffffffffbff (8 bytes)
  //          e_type: elf_types = 0x3 (2 bytes)
  //          e_machine: elf_machines = 0x3e (2 bytes)
  //          e_version: int32 = 0x5 (4 bytes)
  //          e_entry: int64 = 0x3a7 (8 bytes)
  //          e_phoff: bytesize = 0x40 (8 bytes)
  //          e_shoff: int64 = 0x356 (8 bytes)
  //          e_flags: int32 = 0xbbb6 (4 bytes)
  //          e_ehsize: int16 = 0x1 (2 bytes)
  //          e_phentsize: const = 0x38 (2 bytes)
  //          e_phnum: len = 0x0 (2 bytes)
  //          e_shentsize: int16 = 0x3 (2 bytes)
  //          e_shnum: int16 = 0x8 (2 bytes)
  //          e_shstrndx: int16 = 0x44 (2 bytes)
  //        }
  //        phdr: array[elf64_phdr] {
  //        }
  //        data: buffer: {} (length 0x0)
  //        pad: array[buffer] {
  //        }
  //      }
  //    }
  //    len: bytesize = 0x40 (8 bytes)
  //  ]
  *(uint8_t*)0x200000000080 = 0x7f;
  *(uint8_t*)0x200000000081 = 0x45;
  *(uint8_t*)0x200000000082 = 0x4c;
  *(uint8_t*)0x200000000083 = 0x46;
  *(uint8_t*)0x200000000084 = 0x35;
  *(uint8_t*)0x200000000085 = 6;
  *(uint8_t*)0x200000000086 = 5;
  *(uint8_t*)0x200000000087 = 0;
  *(uint64_t*)0x200000000088 = 0xfffffffffffffbff;
  *(uint16_t*)0x200000000090 = 3;
  *(uint16_t*)0x200000000092 = 0x3e;
  *(uint32_t*)0x200000000094 = 5;
  *(uint64_t*)0x200000000098 = 0x3a7;
  *(uint64_t*)0x2000000000a0 = 0x40;
  *(uint64_t*)0x2000000000a8 = 0x356;
  *(uint32_t*)0x2000000000b0 = 0xbbb6;
  *(uint16_t*)0x2000000000b4 = 1;
  *(uint16_t*)0x2000000000b6 = 0x38;
  *(uint16_t*)0x2000000000b8 = 0;
  *(uint16_t*)0x2000000000ba = 3;
  *(uint16_t*)0x2000000000bc = 8;
  *(uint16_t*)0x2000000000be = 0x44;
  syscall(__NR_write, /*fd=*/r[0], /*data=*/0x200000000080ul, /*len=*/0x40ul);
  //  ioctl$VT_RESIZE arguments: [
  //    fd: fd_tty (resource)
  //    cmd: const = 0x5609 (4 bytes)
  //    arg: ptr[in, vt_sizes] {
  //      vt_sizes {
  //        rows: int16 = 0xe2d4 (2 bytes)
  //        cols: int16 = 0x4 (2 bytes)
  //        scroll: int16 = 0xfffa (2 bytes)
  //      }
  //    }
  //  ]
  *(uint16_t*)0x200000000040 = 0xe2d4;
  *(uint16_t*)0x200000000042 = 4;
  *(uint16_t*)0x200000000044 = 0xfffa;
  syscall(__NR_ioctl, /*fd=*/(intptr_t)-1, /*cmd=*/0x5609,
          /*arg=*/0x200000000040ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  do_sandbox_none();
  return 0;
}
